apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    rule_files:
      - "alert_rules.yml"

    alerting:
      alertmanagers:
        - static_configs:
            - targets:
              - alertmanager:9093

    scrape_configs:
      - job_name: 'kubernetes-apiservers'
        kubernetes_sd_configs:
        - role: endpoints
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
        - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
          action: keep
          regex: default;kubernetes;https

      - job_name: 'kubernetes-nodes'
        kubernetes_sd_configs:
        - role: node
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)

      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          target_label: __address__
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: kubernetes_pod_name

      - job_name: 'ukp-api'
        static_configs:
        - targets: ['ukp-api-service:8000']
        metrics_path: /metrics
        scrape_interval: 30s

      - job_name: 'ukp-agents'
        static_configs:
        - targets: ['localhost:8001']
        metrics_path: /metrics
        scrape_interval: 30s

  alert_rules.yml: |
    groups:
    - name: ukp-alerts
      rules:
      - alert: UKPAPIDown
        expr: up{job="ukp-api"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "UKP API is down"
          description: "The UKP API has been down for more than 1 minute"

      - alert: UKPAPIHighLatency
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "UKP API high latency"
          description: "95th percentile latency is above 2 seconds"

      - alert: UKPAPIHighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.05
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "UKP API high error rate"
          description: "Error rate is above 5%"

      - alert: UKPAPIMemoryUsage
        expr: (container_memory_usage_bytes{container="ukp-api"} / container_spec_memory_limit_bytes{container="ukp-api"}) > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "UKP API high memory usage"
          description: "Memory usage is above 80%"

      - alert: UKPAPICPUUsage
        expr: (rate(container_cpu_usage_seconds_total{container="ukp-api"}[5m]) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "UKP API high CPU usage"
          description: "CPU usage is above 80%" 