global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'sarvanom-production'
    region: 'us-west-1'

rule_files:
  - "rules/alerts.yml"
  - "rules/recording.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
      timeout: 10s
      api_version: v2

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s
    metrics_path: '/metrics'

  - job_name: 'sarvanom-backend'
    static_configs:
      - targets: ['sarvanom-backend:8002']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: false
    honor_timestamps: true

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
    metrics_path: '/metrics'

  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']
    metrics_path: '/_prometheus/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'qdrant'
    static_configs:
      - targets: ['qdrant:6333']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'kong'
    static_configs:
      - targets: ['kong:8001']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    metrics_path: '/metrics'

remote_write:
  - url: "http://prometheus-remote-storage:9201/write"
    name: "remote-storage"
    write_relabel_configs:
      - source_labels: [__name__]
        regex: 'go_.*'
        action: drop

remote_read:
  - url: "http://prometheus-remote-storage:9201/read"
    name: "remote-storage" 