# Neo4j Enterprise Helm Chart Configuration
# Universal Knowledge Platform - Knowledge Graph Foundation

neo4j:
  # Enterprise Edition Configuration
  edition: "enterprise"
  version: "5.15.0"
  
  # High Availability Configuration
  resources:
    cpu: "2"
    memory: "4Gi"
    storage: "100Gi"
  
  # Cluster Configuration
  cluster:
    coreNodes: 3
    readReplicas: 2
    password: "${NEO4J_PASSWORD}"
    
  # Security Configuration
  security:
    authEnabled: true
    ssl:
      enabled: true
      certificates:
        secretName: "neo4j-ssl-certs"
    
  # Performance Configuration
  performance:
    pagecache: "2G"
    heapInitial: "1G"
    heapMax: "2G"
    
  # Monitoring Configuration
  monitoring:
    prometheus:
      enabled: true
      port: 2004
    grafana:
      enabled: true
      
  # Backup Configuration
  backup:
    enabled: true
    schedule: "0 2 * * *"  # Daily at 2 AM
    retention: 7  # 7 days
    
  # Network Configuration
  service:
    type: ClusterIP
    ports:
      bolt: 7687
      http: 7474
      https: 7473
      
  # Persistence Configuration
  persistence:
    enabled: true
    storageClass: "fast-ssd"
    size: "100Gi"
    accessMode: ReadWriteOnce
    
  # Security Context
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    
  # Pod Security Context
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000
    
  # Node Selector
  nodeSelector:
    node-type: "database"
    
  # Tolerations
  tolerations:
    - key: "node-type"
      operator: "Equal"
      value: "database"
      effect: "NoSchedule"
      
  # Affinity
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - neo4j
          topologyKey: kubernetes.io/hostname 